version: '3.4'

services:

  api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8443
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
      - "8443:443"  # Porta HTTPS alterada para evitar conflito
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - app-backend
      - shared-network

  api.auth.09:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"
      - "8081:443"  # Mapeamento HTTPS corrigido
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - app-backend

  api.exemple.core.08:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8082
      - ASPNETCORE_URLS=http://+:80
    ports: 
      - "5002:80"
      - "8082:443"  # Mapeamento HTTPS corrigido
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro  
    networks:
      - app-backend
      - shared-network

  api.external.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8083
      - ASPNETCORE_URLS=http://+:80
    ports: 
      - "5003:80"
      - "8083:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - app-backend

  sqlserver:
    ports:
      - "1444:1433"
    networks:
      - app-backend

  redis:
    ports:
      - "6379:6379"  # Redis utilizando a porta correta
    networks:
      - app-backend

  mongoserver:
    ports:
      - "27017:27017"  
    networks:
      - app-backend

  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672  
    networks:
      - app-backend

  zookeeper:
    networks:
      - app-backend

  kafka1:
    networks:
      - app-backend

  kafka-ui:
    networks:
      - app-backend

