version: '3.4'

services:

  api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8443
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
      - "8443:443"  # Porta HTTPS alterada para evitar conflito
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - app-backend

  api.auth.09:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:80
      
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Integrated Security=true;Initial Catalog=apiauth_docker;User Id=sa;Password=@Poc2Minimal@Api;Trusted_Connection=false;MultipleActiveResultSets=true;Encrypt=True;TrustServerCertificate=True;
      - ConnectionStrings__CacheConnection=Redis,password=Poc2Minimal@Api
      
      - MongoDB__ConnectionString=mongodb://mongoserver:27017
      - MongoDB__Database=apiauth_docker

      - Serilog__WriteTo__Name=MongoDB
      - Serilog__WriteTo__Args__databaseUrl=mongodb://mongoserver:27017/admin
      - Serilog__WriteTo__Args__collectionName=apiauth_docker
      - Serilog__WriteTo__Args__cappedMaxSizeMb=1024
      - Serilog__WriteTo__Args__cappedMaxDocuments=50000
      
      - Kafka__BootstrapServers=kafka1:9092
      - Kafka__DefaultTopic=integration-events

      - RabbitMQ__Hostname=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__VirtualHost="/"
    ports:
      - "5001:80"
      - "8081:443"  # Mapeamento HTTPS corrigido
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - app-backend

  api.exemple.core.08:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8082
      - ASPNETCORE_URLS=http://+:80
    ports: 
      - "5002:80"
      - "8082:443"  # Mapeamento HTTPS corrigido
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro  
    networks:
      - app-backend

  sqlserver:
    ports:
      - "1444:1433"
    networks:
      - app-backend

  redis:
    ports:
      - "6379:6379"  # Redis utilizando a porta correta
    networks:
      - app-backend

  mongoserver:
    ports:
      - "27017:27017"  
    networks:
      - app-backend

  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672  
    networks:
      - app-backend

  zookeeper:
    networks:
      - app-backend

  kafka1:
    networks:
      - app-backend

  kafka-ui:
    networks:
      - app-backend
