version: '3.9'

networks:
  app-send-menssage:
    driver: bridge

services:

  poc.api.redis-webapi:
    image: ${DOCKER_REGISTRY-}poc.api.redis-webapi
    container_name: poc.api.redis-webapi
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5074
    ports:
      - 5074:5074
    links:
      - redis
    networks:
      - app-send-menssage
    depends_on:
      - redis
      
  # Redis Cache Server
  redis:
    image: redis:latest
    container_name: redissend
    command: redis-server --requirepass Poc2Minimal@Api
    restart: always
    expose:
      - 6379
    ports:
      - 6380:6379
    networks:
      - app-send-menssage
